/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udloansmis;

import DTO.ComponentDTO;
import DTO.LoanDTO;
import DTO.StudentDTO;
import RMI.IDatabaseRMI;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigInteger;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import security.TokenHandlerClient;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class UdloansMis_UdlånsMis extends javax.swing.JFrame {

    private final UdloansMis_Dato dato = new UdloansMis_Dato(this);
    private final String serverIP;
    private final JFrame logFrame;
    private UdloansMis_Log logPanel;
    private boolean logEnabled = false;
    private UdloansMis_CheckForServer checkforserver;
    private final TokenHandlerClient tokenhandler;
    private IDatabaseRMI database;

    public UdloansMis_UdlånsMis(TokenHandlerClient tokenhandler, IDatabaseRMI database, String serverIP) {
        this.logFrame = new JFrame("UdlånsMis v1.0 Log");
        this.tokenhandler = tokenhandler;
        this.database = database;
        this.serverIP = serverIP;
    }

    public void init() {
        initComponents();
        Thread dateThread = new Thread(dato);
        dateThread.start();
        checkforserver = new UdloansMis_CheckForServer(this, tokenhandler, database, serverIP);
        Thread checkForServerThread = new Thread(checkforserver);
        checkForServerThread.start();
        startLog();
    }

    public void CheckServer(boolean isConnectedToServer) {
        if (isConnectedToServer == true) {
            jTextFieldServerCheck.setForeground(new java.awt.Color(255, 255, 255));
            jTextFieldServerCheck.setBackground(new java.awt.Color(0, 150, 0));
            jTextFieldServerCheck.setText("Forbundet til komponentserver på " + serverIP);
        } else {
            jTextFieldServerCheck.setForeground(new java.awt.Color(255, 255, 255));
            jTextFieldServerCheck.setBackground(new java.awt.Color(150, 0, 0));

            jTextFieldServerCheck.setText("Ikke forbundet til komponentserver, automatisk genoprettelse foregår");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldStregkode = new javax.swing.JTextField();
        jTextFieldStudieNr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldServerCheck = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButtonLog = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldStregkode.setText("Stregkode eller navn");
        jTextFieldStregkode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldStregkodeMouseClicked(evt);
            }
        });
        jTextFieldStregkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStregkodeActionPerformed(evt);
            }
        });

        jTextFieldStudieNr.setText("Sxxxxxx");
        jTextFieldStudieNr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldStudieNrMouseClicked(evt);
            }
        });
        jTextFieldStudieNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudieNrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Scan eller søg efter komponent");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Studienummer");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel3.setText("UdlånsMis v1.0");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Søg i database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Dato");

        jTextFieldServerCheck.setEditable(false);
        jTextFieldServerCheck.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldServerCheck.setText("ServerCheck");
        jTextFieldServerCheck.setFocusable(false);
        jTextFieldServerCheck.setRequestFocusEnabled(false);
        jTextFieldServerCheck.setVerifyInputWhenFocusTarget(false);

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Navn", "Stregkodenummer", "Studienummer", "Udlånsdato", "Afleveringsdato", "Dage til aflevering"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setFocusable(false);
        jTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Udlån");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Aflevering");
        jButton3.setActionCommand("Aflever");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jRadioButtonLog.setText("Log");
        jRadioButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldStregkode, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 388, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldStudieNr, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldServerCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonLog))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStregkode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStudieNr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldServerCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jTextFieldStregkode, jTextFieldStudieNr});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStregkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStregkodeActionPerformed

        try {
            søgUdlån(jTextFieldStregkode.getText());
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }
    }//GEN-LAST:event_jTextFieldStregkodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            søgUdlån(jTextFieldStregkode.getText());
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }

        /* if (checkforserver.isConnectedToServer) {
            String stregkode = jTextFieldStregkode.getText();
            String studienummer = jTextFieldStudieNr.getText();
            if (!stregkode.equals("Stregkode eller navn")) {
                StringSelection stringSelection = new StringSelection(stregkode);
                Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
                clpbrd.setContents(stringSelection, null);

            } else if ((studienummer.length() == 7) && (!studienummer.equals("Sxxxxxx"))) {
                if (studienummer.startsWith("S") || studienummer.startsWith("s")) {
                    String studietalString = studienummer.substring(1, 7);

                    if (!studietalString.matches("^\\d+$")) {   // Check om der er bogstaver i studienummeret.
                        String st = "Studienummer ukorrekt.";
                        JOptionPane.showMessageDialog(null, st);

                    } else {
                        System.out.print("Det indtastede studienummer er: S" + studietalString + "\n");

                        StringSelection stringSelection = new StringSelection(studienummer);
                        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
                        clpbrd.setContents(stringSelection, null);
                        jTextFieldStudieNr.setText("Sxxxxxx");
                    }
                } else {
                    String st = "Scan stregkode, skriv navn eller studienummer, og klik på søg.";
                    JOptionPane.showMessageDialog(null, st);

                }

            }

        } else {
            String st = "Ikke forbundet til serveren. Check kabler, forbindelsen genoprettes automatisk";
            JOptionPane.showMessageDialog(null, st);
            jTable.setValueAt("12345678", 3, 0);
            jTable.setValueAt("Zybo kit #16", 3, 1);
            jTable.setValueAt("19/4-2016", 3, 2);
            jTable.setValueAt("19/6-2016", 3, 3);
            jTable.setValueAt("61", 3, 4);
            //jTable2.setBackground(Color.red);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Dato skal være i dette format 
        // ***** "24/2-16" *******

        // **** Dags dato ****
        Date curDate = new Date();
        SimpleDateFormat format = new SimpleDateFormat();
        String curDateString = format.format(curDate);
//        System.out.println("1: Default pattern: " + dateToStr);
        format = new SimpleDateFormat("dd/MM-yy");
        curDateString = format.format(curDate);
//        System.out.println("2: Dansk pattern = " + dateToStr);
        Date strToDate = null;
        try {
            strToDate = format.parse(curDateString);
        } catch (ParseException ex) {
            logPanel.println("Forkert dato-input");
        }
//        System.out.println("3: " + strToDate);
        String text = "";
        String stregkode = "";
        String studieNummer = "";
        String afleveringsDato = "";
        // **** Afleveringsdato fra inputboks ****    
        int aflevÅr = 0;
        int aflevMån = 0;
        int aflevDag = 0;
        int dageTilAflevering = 0;
        Date afleveringsDatoFinal = new Date();

        try {
            LoanDTO[] test = database.getLoansForBarcode(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }

        text = "Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 123456789)";
        while (true) {
            stregkode = JOptionPane.showInputDialog(null, text);
            if (stregkode == null) {
                JOptionPane.showMessageDialog(null, "Udlånet er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            text = "Forkert stregkode-input. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 123456789)";

            if (stregkode.matches("^([0-9]{6,10})$")) {
                try {
                    logPanel.println("Indtastet stregkode: " + stregkode);
                    ComponentDTO component = database.getComponent(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
                    LoanDTO[] loans = database.getLoansForBarcode(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
                    if (component == null) {
                        text = "Komponenten findes ikke. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                        continue;
                    }
                    if (component.getStatus() != 1) {
                        text = "Komponenten er inaktiv. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                        continue;
                    }
                    if (loans != null) { // first time loaned check
                        boolean isLoaned = false;
                        for (LoanDTO loan : loans) {
                            if (loan.getDeliveryDate() == null) {
                                isLoaned = true;
                                break;
                            }
                        }
                        if (isLoaned) { // check if any loan currently active
                            text = "Komponenten er allerede lånet ud. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                            continue;
                        }
                    }
                    break;

                } catch (RemoteException ex) {
                    logPanel.println("Fejl ved kommunikation." + ex.getMessage());
                }
            }

        }

        text = "Læg studiekortet på RFID læser, eller indtast studienummer. (Ex. s123456)";
        while (true) {
            studieNummer = JOptionPane.showInputDialog(null, text);
            if (studieNummer == null) {
                JOptionPane.showMessageDialog(null, "Udlånet er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            text = "Forkert studienummer-input. Læg studiekortet på RFID læser, eller indtast studienummer. (Ex. s123456)";
            logPanel.println("Indtastet studienummer: " + studieNummer);
            if (studieNummer.matches("^([sS][0-9]{6})$")) {
                StudentDTO student = null;
                try {
                    student = database.getStudent(studieNummer, tokenhandler.getKeyToken(), tokenhandler.getID());
                    if (student == null) {
                        text = "Studienumeret findes ikke. Læg studiekortet på RFID læser, eller indtast studienummer. (Ex. s123456)";
                    } else if (student.getStatus() != 1) {
                        text = "Studienumeret er inaktiv. Læg studiekortet på RFID læser, eller indtast studienummer. (Ex. s123456)";
                    } else {
                        break;
                    }
                } catch (RemoteException ex) {
                    logPanel.println("Fejl ved kommunikation." + ex.getMessage());
                }
            }

        }

        text = "Indtast afleveringsdato i dette format dd/MM-yy. (Ex. " + curDateString + ")";
        while (true) {
            afleveringsDato = JOptionPane.showInputDialog(null, text);
            if (afleveringsDato == null) {
                JOptionPane.showMessageDialog(null, "Udlånet er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            text = "Forkert dato-input. Indtast afleveringsdato i dette format dd/MM-yy. (Ex. " + curDateString + ")";
            logPanel.println("Indtastet dato: " + afleveringsDato);
            if (afleveringsDato.matches("^(0?[1-9]|[12][0-9]|3[01])[/](0?[1-9]|1[012])[-](20)?[0-9][0-9]$")) {
                aflevDag = Integer.parseInt(afleveringsDato.substring(0, afleveringsDato.indexOf("/")));
                aflevMån = Integer.parseInt(afleveringsDato.substring(afleveringsDato.indexOf("/") + 1, afleveringsDato.indexOf("-")));
                aflevÅr = Integer.parseInt("20" + afleveringsDato.substring(afleveringsDato.length() - 2));
                if (aflevDag == 31 && (aflevMån == 4 || aflevMån == 6 || aflevMån == 9 || aflevMån == 11)) // aflevMåns with 31 aflevDags
                {
                } else if (aflevDag >= 30 && aflevMån == 2) // feb must be <= 28
                {
                } else if (aflevMån == 2 && aflevDag == 29 && !(aflevÅr % 4 == 0 && (aflevÅr % 100 != 0 || aflevÅr % 400 == 0))) // feb must only be 29 if it's a leap aflevÅr
                {
                } else {
                    String afleveringsdatoString = "" + aflevDag + "/" + aflevMån + "-" + aflevÅr;
                    // **** Dato 2 ****
                    SimpleDateFormat format2 = new SimpleDateFormat();
                    format2 = new SimpleDateFormat("dd/MM-yy");
                    try {
                        afleveringsDatoFinal = format2.parse(afleveringsdatoString);
                        afleveringsDatoFinal.setTime(afleveringsDatoFinal.getTime() + 86400000); // add 12 hours
                        System.out.println(afleveringsdatoString);
                        System.out.println(afleveringsDatoFinal);
                        // *** Beregn antal dage til aflevering. ****
                        dageTilAflevering = (int) ((afleveringsDatoFinal.getTime() - curDate.getTime()) / 86400000) + 1;
                        if (dageTilAflevering < 0) {
                            text = "Forældet dato. Indtast afleveringsdato i dette format dd/MM-yy. (Ex. " + curDateString + ")";
                        } else {
                            break;
                        }
                    } catch (ParseException ex) {
                        logPanel.println("Forkert dato-input");
                    }
                }
            }
        }

        String resumeTekstBoks = "Ønsker du at lave et udlån af følgende komponent?\n"
                + "Stregkode: " + stregkode + ", til " + studieNummer + " i " + dageTilAflevering + " dage?";
        Object[] options = {"Bekræft", "Afbryd"};

        // Bekræftelse
        int n = JOptionPane.showOptionDialog(null,
                resumeTekstBoks,
                "Bekræft udlån",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        // n er 0 ved Bekræft, og 1 ved Afbryd
        if (n == 0) {
            opretUdlån(stregkode, studieNummer, curDate, afleveringsDatoFinal);
            // Send til RMI og vis nedenstående besked.
        } else {
            //Send ikke noget til RMI
            JOptionPane.showMessageDialog(null, "Udlånet er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String text = "";
        String stregkode = "";
        String credentials = "";
        ComponentDTO component;
        text = "Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 123456789)";
        while (true) {
            stregkode = JOptionPane.showInputDialog(null, text);
            if (stregkode == null) {
                JOptionPane.showMessageDialog(null, "Aflevereringen er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            text = "Forkert stregkode-input. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
            if (stregkode.matches("^([0-9]{6,10})$")) {
                logPanel.println("Indtastet stregkode: " + stregkode);
                try {
                    component = database.getComponent(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
                    if (component == null) {
                        text = "Komponenten findes ikke. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                        continue;
                    }
                    LoanDTO[] loans = database.getLoansForBarcode(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
                    if (loans == null) { // first time loaned check
                        text = "Komponenten er ikke lånet ud. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                        continue;
                    } else {
                        boolean isLoaned = false;
                        for (LoanDTO loan : loans) {
                            if (loan.getDeliveryDate() == null) {
                                isLoaned = true;
                                break;
                            }
                        }
                        if (!isLoaned) { // check if any loan currently active
                            text = "Komponenten er ikke lånet ud. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
                            continue;
                        }
                    }

                    break;

                } catch (RemoteException ex) {
                    logPanel.println("Fejl ved kommunikation." + ex.getMessage());
                }
            }
        }

        text = "Returneret til: (Indtast navn)";
        while (true) {
            credentials = JOptionPane.showInputDialog(null, text);
            if (credentials == null) {
                JOptionPane.showMessageDialog(null, "Aflevereringen er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            text = "Forkert stregkode-input. Scan eller indtast stregkodenummer på udlånskomponent. (Ex. 12345678)";
            if (credentials.matches("^([0-9]{6,10})$")) {
                logPanel.println("Indtastet stregkode: " + credentials);
                break;
            }
        }

        // Bekræftelse
        String resumeTekstBoks = "Ønsker du at aflevere følgende komponent?\n"
                + "Stregkode: " + stregkode + ", komponent navn: " + component.getComponentGroup().getName() + "?";
        Object[] options = {"Bekræft", "Afbryd"};
        int n = JOptionPane.showOptionDialog(null,
                resumeTekstBoks,
                "Bekræft udlån",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        // n er 0 ved Bekræft, og 1 ved Afbryd
        if (n == 0) {
            opretAflevering(stregkode);
            // Send til RMI og vis nedenstående besked.
        } else {
            //Send ikke noget til RMI
            JOptionPane.showMessageDialog(null, "Aflevereringen er afbrudt.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldStudieNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudieNrActionPerformed
        try {
            søgStudieNr(jTextFieldStudieNr.getText());
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }
    }//GEN-LAST:event_jTextFieldStudieNrActionPerformed

    private void jRadioButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLogActionPerformed
        setLog();
    }//GEN-LAST:event_jRadioButtonLogActionPerformed

    private void jTextFieldStudieNrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldStudieNrMouseClicked
        jTextFieldStudieNr.setText("");
    }//GEN-LAST:event_jTextFieldStudieNrMouseClicked

    private void jTextFieldStregkodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldStregkodeMouseClicked
        jTextFieldStregkode.setText("");
    }//GEN-LAST:event_jTextFieldStregkodeMouseClicked

    public void setDate(String date) {
        jLabel5.setText(date);
    }

    private void søgUdlån(String keyword) throws RemoteException {
        for (int i = 0; i < jTable.getRowCount(); i++) {
            for (int j = 0; j < jTable.getColumnCount(); j++) {
                jTable.setValueAt("", i, j);
            }
        }
        try {
            LoanDTO[] loans = database.searchLoans(keyword, tokenhandler.getKeyToken(), tokenhandler.getID());
            for (int i = 0; i < loans.length; i++) {
                jTable.setValueAt(loans[i].getComponent().getComponentGroup().getName(), i, 0);
                jTable.setValueAt(loans[i].getBarcode(), i, 1);
                jTable.setValueAt(loans[i].getStudentId(), i, 2);
                jTable.setValueAt(loans[i].getLoanDate(), i, 3);
                jTable.setValueAt(loans[i].getDueDate(), i, 4);
                Date curDate = new Date();
                double msPerDay = 86400 * 1000;
                int dageTilAflevering = (int) ((loans[i].getDueDateAsDate().getTime() - curDate.getTime()) / msPerDay) + 1;
                jTable.setValueAt(Integer.toString(dageTilAflevering), i, 5);
            }
        } catch (NullPointerException ex) {
            logPanel.println("Fejl i indtastning.");
        }
    }

    private void søgStudieNr(String keyword) throws RemoteException {
        for (int i = 0; i < jTable.getRowCount(); i++) {
            for (int j = 0; j < jTable.getColumnCount(); j++) {
                jTable.setValueAt("", i, j);
            }
        }
        try {
            LoanDTO[] loans = database.getLoansForStudent(keyword, tokenhandler.getKeyToken(), tokenhandler.getID());
            for (int i = 0; i < loans.length; i++) {
                jTable.setValueAt(loans[i].getComponent().getComponentGroup().getName(), i, 0);
                jTable.setValueAt(loans[i].getBarcode(), i, 1);
                jTable.setValueAt(loans[i].getStudentId(), i, 2);
                jTable.setValueAt(loans[i].getLoanDate(), i, 3);
                jTable.setValueAt(loans[i].getDueDate(), i, 4);
                Date curDate = new Date();
                double msPerDay = 86400 * 1000;
                int dageTilAflevering = (int) ((loans[i].getDueDateAsDate().getTime() - curDate.getTime()) / msPerDay) + 1;
                jTable.setValueAt(Integer.toString(dageTilAflevering), i, 5);
            }
        } catch (NullPointerException ex) {
            logPanel.println("Der er ikke registreret lån under denne bruger");
        }
    }

    private void opretUdlån(String barcode, String studentId, Date loanDate, Date dueDate) {
        try {
            LoanDTO loan = new LoanDTO();
            loan.setComponent(database.getComponent(barcode, tokenhandler.getKeyToken(), tokenhandler.getID()));
            loan.setBarcode(barcode);
            loan.setStudentId(studentId);
            loan.setLoanDateFromDate(loanDate);
            loan.setDueDateFromDate(dueDate);

            int OK = database.createLoan(loan, tokenhandler.getKeyToken(), tokenhandler.getID());
            if (OK == 1) {
                logPanel.println("Udlånet er gennemført. OK:" + OK);
                JOptionPane.showMessageDialog(null, "Udlånet er gennemført.");
            } else if (OK == -2 || OK == -1 || OK == 0) {
                logPanel.println("Fejl ved kommunikation. OK:" + OK);
                JOptionPane.showMessageDialog(null, "Fejl ved kommunikation.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }
    }

    private void opretAflevering(String stregkode) {
        try {
            LoanDTO[] loans = database.getLoansForBarcode(stregkode, tokenhandler.getKeyToken(), tokenhandler.getID());
            if (loans == null) {
                logPanel.println("Lån med stregkode: " + stregkode + " kan ikke findes.");
                JOptionPane.showMessageDialog(null, "Lån med stregkode: " + stregkode + " kan ikke findes.");
                return;
            }
            LoanDTO loan = loans[0];
            if (loan == null) {
                logPanel.println("Lån med stregkode: " + stregkode + " kan ikke findes.");
                JOptionPane.showMessageDialog(null, "Lån med stregkode: " + stregkode + " kan ikke findes.");
                return;
            }
            int loanid = loan.getLoanId();

            // **** Dags dato ****
            Date curDate = new Date();
            SimpleDateFormat format = new SimpleDateFormat();
            format = new SimpleDateFormat("dd/MM-yy");
            String curDateString = format.format(curDate);

            loan = database.getLoan(loanid, tokenhandler.getKeyToken(), tokenhandler.getID());
            loan.setDeliveryDate(curDateString);
            loan.setDeliveryDateFromDate(curDate);
            loan.setDeliveredTo("TEST");
            int OK = database.updateLoan(loan, tokenhandler.getKeyToken(), tokenhandler.getID());
//            int OK2 = database.deleteLoan(loanid, tokenhandler.getKeyToken(), tokenhandler.getID());
            logPanel.println("Loan object: " + loan);
            logPanel.println("Loan ID: " + loanid);
            logPanel.println("Loan linked barcode: " + stregkode);
            if (OK == 1) {
                logPanel.println("Aflevereringen er gennemført. OK: " + OK);
                JOptionPane.showMessageDialog(null, "Aflevereringen er gennemført.");
            } else if (OK == -2 || OK == -1 || OK == 0) {
                logPanel.println("Fejl ved kommunikation. OK: " + OK);
                JOptionPane.showMessageDialog(null, "Fejl ved kommunikation.", "Bemærk!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            logPanel.println("Fejl ved kommunikation." + ex.getMessage());
        }
    }

    private void startLog() {

        // Create jPanel
        logPanel = new UdloansMis_Log();

        // Add panel to window
        logFrame.add(logPanel);
        logFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        logFrame.setSize(570, 650);

        // Add windowListener to check for window closing;
        logFrame.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                logEnabled = false;
                jRadioButtonLog.setSelected(false);
            }
        });
    }

    private void setLog() {
        if (!logEnabled) {
            // Show window
            logFrame.setVisible(true);
            logEnabled = true;
        } else {
            logFrame.setVisible(false);
            logEnabled = false;
        }
    }

    public void setDatabase(IDatabaseRMI database) {
        this.database = database;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLog;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldServerCheck;
    private javax.swing.JTextField jTextFieldStregkode;
    private javax.swing.JTextField jTextFieldStudieNr;
    // End of variables declaration//GEN-END:variables

}
